apiVersion: v1
kind: ServiceAccount
metadata:
  name: nvidia-driver-installer-ubuntu
  namespace: kube-system
  labels:
    app: nvidia-driver-installer-ubuntu
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nvidia-driver-installer-ubuntu
  labels:
    app: nvidia-driver-installer-ubuntu
subjects:
  - kind: ServiceAccount
    name: nvidia-driver-installer-ubuntu
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: nvidia-driver-installer-ubuntu
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nvidia-driver-installer-ubuntu
  labels:
    app: nvidia-driver-installer-ubuntu
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["nodes", "pods"]
    verbs: ["*"]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-driver-installer-ubuntu
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: nvidia-driver-installer-ubuntu
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nvidia-driver-installer-ubuntu
    spec:
      serviceAccountName: nvidia-driver-installer-ubuntu
      hostNetwork: true
      hostPID: true
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: root-mount
          hostPath:
            path: /
      initContainers:
        - name: nvidia-driver-installer-ubuntu
          image: "ubuntu:20.10"
          command: ["/usr/sbin/chroot", "/root", "/bin/bash"]
          env:
            - name: NVIDIA_DRIVER_VERSION
              value: "470"
          args:
            - -exc
            - |
              export DEBIAN_FRONTEND=noninteractive
              dpkg --add-architecture i386
              apt-get update -y

              # Install Nvidia driver
              apt install -y --no-install-recommends \
                build-essential dkms \
                nvidia-driver-${NVIDIA_DRIVER_VERSION} \
                libnvidia-gl-${NVIDIA_DRIVER_VERSION}:i386 \
                libnvidia-compute-${NVIDIA_DRIVER_VERSION}:i386

              # Install kernel modules
              modprobe nvidia-drm modeset=0
              modprobe nvidia
              modprobe nvidia-uvm
              modprobe nvidia-modeset

              # Verify installation
              nvidia-smi

              # https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/176ef225b975c536ac31c1155fd33c3122cdb732/cmd/nvidia_gpu/nvidia_gpu.go#L39
              export NVIDIA_DST_DIR=/home/kubernetes/bin/nvidia
              mkdir -p ${NVIDIA_DST_DIR}

              mkdir -p ${NVIDIA_DST_DIR}/bin
              ls -1 /usr/bin/nvidia* | xargs -i cp {} ${NVIDIA_DST_DIR}/bin/

              mkdir -p ${NVIDIA_DST_DIR}/lib32
              ls -1 /usr/lib/i386-linux-gnu/{libGL*,libEGL*,libnv*,libcuda*} | xargs -i cp {} ${NVIDIA_DST_DIR}/lib32/

              mkdir -p ${NVIDIA_DST_DIR}/lib64
              ls -1 /usr/lib/x86_64-linux-gnu/{libGL*,libEGL*,libnv*,libcuda*} | xargs -i cp {} ${NVIDIA_DST_DIR}/lib64/

              mkdir -p ${NVIDIA_DST_DIR}/drivers
              ls -1 /lib/modules/"$(uname -r)"/updates/dkms/* | xargs -i cp {} ${NVIDIA_DST_DIR}/drivers/

              # https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/176ef225b975c536ac31c1155fd33c3122cdb732/cmd/nvidia_gpu/nvidia_gpu.go#L41
              export VULKAN_ICD_DST_DIR=/home/kubernetes/bin/nvidia/vulkan/icd.d
              mkdir -p ${VULKAN_ICD_DST_DIR}
              cp /usr/share/vulkan/icd.d/* ${VULKAN_ICD_DST_DIR}/

              touch /tmp/nvidia_driver_install_complete

          resources:
            requests:
              cpu: 150m
          securityContext:
            privileged: true
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: root-mount
              mountPath: /root

      containers:
        - image: "gcr.io/google-containers/pause:2.0"
          name: pause
