apiVersion: v1
kind: ServiceAccount
metadata:
  name: nvidia-driver-installer-ubuntu
  namespace: kube-system
  labels:
    app: nvidia-driver-installer-ubuntu
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nvidia-driver-installer-ubuntu
  labels:
    app: nvidia-driver-installer-ubuntu
subjects:
  - kind: ServiceAccount
    name: nvidia-driver-installer-ubuntu
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: nvidia-driver-installer-ubuntu
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nvidia-driver-installer-ubuntu
  labels:
    app: nvidia-driver-installer-ubuntu
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["nodes", "pods"]
    verbs: ["*"]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-driver-installer-ubuntu
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: nvidia-driver-installer-ubuntu
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nvidia-driver-installer-ubuntu
    spec:
      serviceAccountName: nvidia-driver-installer-ubuntu
      hostNetwork: true
      hostPID: true
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: root-mount
          hostPath:
            path: /
      initContainers:
        - name: nvidia-driver-installer-ubuntu
          image: "ubuntu:20.10"
          command: ["/usr/sbin/chroot", "/root", "/bin/bash"]
          env:
            - name: NVIDIA_DRIVER_VERSION
              value: "470"
          args:
            - -exc
            - |
              export DEBIAN_FRONTEND=noninteractive
              dpkg --add-architecture i386
              apt-get update -y

              # Install as many of the dependencies as possible before mounting
              # the overlayfs to reduce the number of bins and libs that will be mounted
              # into runtime containers.
              apt-get install -y --no-install-recommends \
                  build-essential \
                  dkms \

              # Install Nvidia driver
              apt install -y --no-install-recommends \
                nvidia-driver-${NVIDIA_DRIVER_VERSION} \
                libnvidia-encode-${NVIDIA_DRIVER_VERSION} \
                libnvidia-common-${NVIDIA_DRIVER_VERSION} \
                libnvidia-gl-${NVIDIA_DRIVER_VERSION}:i386 \
                libnvidia-compute-${NVIDIA_DRIVER_VERSION}:i386

              # Install kernel modules
              modprobe nvidia-drm modeset=0
              modprobe nvidia
              modprobe nvidia-uvm
              modprobe nvidia-modeset

              # Verify installation
              nvidia-smi

              touch /tmp/nvidia_driver_install_complete

          resources:
            requests:
              cpu: 150m
          securityContext:
            privileged: true
          volumeMounts:
            - name: dev
              mountPath: /dev
            - name: root-mount
              mountPath: /root

      containers:
        - image: "gcr.io/google-containers/pause:2.0"
          name: pause
