kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kindgpu
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        "service-node-port-range": "1000-65535"
nodes:
  - role: control-plane
    image: kindest/node:v1.18.15
  - role: worker
    image: kindest/node:v1.18.15
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "cloud.google.com/gke-accelerator=true"
    extraMounts:
      - hostPath: ./apps
        containerPath: /apps
        readOnly: true
    extraPortMappings:
      - containerPort: 5900
        hostPort: 5900
        listenAddress: "127.0.0.1"
