apiVersion: v1
kind: Pod
metadata:
  name: vulkan-pod
  labels:
    component: vnc
spec:
  volumes:
    - name: x11
      emptyDir:
        medium: Memory
        sizeLimit: 10Mi
  containers:
    - name: app
      image: vulkan-app:fixed
      command: ["vkcube"]
      env:
        - name: DISPLAY
          value: ":0"
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: all
      volumeMounts:
        - name: x11
          mountPath: /tmp/.X11-unix
    - name: xserver
      image: xserver:fixed
      env:
        - name: DISPLAY
          value: ":0"
      ports:
        - name: x11vnc
          containerPort: 5900
      volumeMounts:
        - name: x11
          mountPath: /tmp/.X11-unix
---
kind: Service
apiVersion: v1
metadata:
  name: vnc
spec:
  selector:
    component: vnc
  type: NodePort
  ports:
    - name: vnc
      port: 5900
      nodePort: 5900