apiVersion: v1
kind: Pod
metadata:
  name: vulkan-pod
spec:
  volumes:
    - name: x11
      emptyDir:
        medium: Memory
        sizeLimit: 10Mi
  containers:
    - name: app
      image: ghcr.io/castaneai/vulkan-app:fixed
      command: ["vkcube"]
      env:
        - name: DISPLAY
          value: ":0"
        # for GCP nvidia device plugin
        # https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/176ef225b975c536ac31c1155fd33c3122cdb732/cmd/nvidia_gpu/nvidia_gpu.go#L40
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib64
      volumeMounts:
        - name: x11
          mountPath: /tmp/.X11-unix
      resources:
        limits:
          nvidia.com/gpu: "1"
    - name: xserver
      image: ghcr.io/castaneai/xserver:fixed
      env:
        - name: DISPLAY
          value: ":0"
      ports:
        - name: x11vnc
          containerPort: 5900
      volumeMounts:
        - name: x11
          mountPath: /tmp/.X11-unix